name: pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [17.x]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Init
        run: npm init
      - name: Build
        run: npm run build:prod
      - name: Typescript lint
        run: npm run lint:ts
      - name: 'Styles ling'
        run: npm run lint:scss
      - name: 'Unit test'
        run: npm run test:unit
